[package]
name = "pnetlink"
version = "0.1.0"
authors = ["root"]
build = "build.rs"


[build-dependencies.pnet_macros]
git = "https://github.com/polachok/libpnet"
branch = "le"
features = [ "with-syntex" ]

[dependencies.pnet_macros_support]
version = "0.1.0"

[dependencies.pnet]
version = "0.9.0"

[build-dependencies.syntex]
version = "0.31"

[dependencies]
libc = "0.2"

[dependencies]
rand = "0.3.14"
bitflags = "0.7"
